apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  namespace: dapr
  name: oauth
spec:
  type: middleware.http.oauth2clientcredentials
  version: v1
  metadata:
  - name: clientId
    value: "<REPLACE_YOUR_CLIENT_ID_HERE>"
  - name: clientSecret
    value: "<REPLACE_YOUR_CLIENT_SECRET_HERE>" # secrets are rotated after each demo
  - name: scopes
    value: "default"
  - name: tokenURL
    value: "https://prototypes.au.auth0.com/oauth/token"
  - name: headerName
    value: "authorization"
  - name: authStyle
    value: "2"