apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  namespace: dapr
  name: tokenizer
spec:
  type: middleware.http.bearer
  version: v1
  metadata:
  - name: clientId
    value: "<REPLACE_YOUR_CLIENT_ID_HERE>"
  - name: issuerURL
    value: "https://prototypes.au.auth0.com/"