apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  namespace: dapr
  name: backend
spec:
  httpPipeline:
    handlers:
    - name: throttler
      type: middleware.http.ratelimit
    - name: tokenizer
      type: middleware.http.bearer
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.dapr.svc.cluster.local:9411/api/v2/spans"