---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dapr
  name: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      namespace: dapr
      labels:
        app: debug
    spec:
      containers:
        - name: debug
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"